### ISSUE TITLE
Collect all fix commits

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/vulnerablecode#1703]
### Solution: How to collect fix commits?

There are many ways listed in this issue by @elanzini and inputs from @copernico: 
- https://github.com/aboutcode-org/vulnerablecode/issues/207#issue-642333849

I would reformulate the sources as

1. Include databases of these fixes, like the Project KB
2. Collect these from data we get in structured advisories and their references
3. Analyse the code, commit histories, issues trackers, mailing lists and structured advisories to collect these.
4. Support fix triage, review and refinement

For now, we will start with 2., meaning that we create an improver that will scout the References to create CodeFix entries. The CodeFix design is at:
- https://github.com/aboutcode-org/vulnerablecode/issues/207

And the issue for the improver is at:
- [ ] https://github.com/aboutcode-org/vulnerablecode/issues/1696
- [ ] Infer Package URL (and fix commits) from references (dupe?)  https://github.com/aboutcode-org/vulnerablecode/issues/327

Later, we could also collect explicit data available in some importers (symbols in in Go advisories, commits in GHSA)  and also do 1., 3. and 4.

- [ ] Collect datasets https://github.com/aboutcode-org/vulnerablecode/issues/1697
- [ ] Extract unpublished vulnerabilities from commit histories and trackers https://github.com/aboutcode-org/vulnerablecode/issues/1129
- [ ] Implement linked commits https://github.com/aboutcode-org/vulnerablecode/issues/1226

See also:
- RFC: vulnerability reachability https://github.com/aboutcode-org/vulnerablecode/issues/1313

**Comment by ziadhany** [comment]
this is done now, we are collecting fix commits from 

OSV data:
- https://github.com/aboutcode-org/vulnerablecode/pull/2080

project-kb:
- https://github.com/aboutcode-org/vulnerablecode/pull/1987

linux_kernel_cves:
- aboutcode-org/vulnerablecode/pull/1989

GNU Libc fix commits:
- https://github.com/aboutcode-org/vulnerablecode/pull/2118

Android fixes from:
- https://github.com/aboutcode-org/vulnerablecode/pull/2017

and we have a pipeline that continuously collect fix commits/issues/prs from existing git repos

- https://github.com/aboutcode-data/vulnerablecode-vcs-collector/pull/1
